spring:
  cloud:
    gateway:
      routes:
        - id: gateway-server01 #id是唯一的
          #uri: lb://GATEWAY-CLIENT #被代理的服务的uri
          uri: http://127.0.0.1:10010
          predicates:
          - Path=/api/client/**
          #- Weight=service,1
          - Cookie=authcode, (.*)
          #- Method= POST
          #- Header=test,(.*?)
          filters:
          - StripPrefix=2
          #- name: RequestRateLimiter
            #args:
                #keyResolver: "#{@remoteAddrKeyResolver}"
                #redis-rate-limiter.replenishRate: 1 #单位时间允许内执行请求的个数
                #redis-rate-limiter.burstCapacity: 2 #单位时间内允许向桶中放入令牌的数量
